version: '3.8'

services:
  frontend:
    build:
      context: ./fronted
    container_name: smart-academic-frontend
    ports:
      - "8080:80"
    networks:
      - smart-campus

networks:
  smart-campus:
    external: true
