server {
    listen 80;
    server_name localhost;

    # Servir archivos estáticos del frontend
    location / {
        root /usr/share/nginx/html;
        index index.html dashboard.html;
        # CORRECCIÓN: Si piden dashboard.html, busca dashboard.html. Si no existe nada, vuelve a index.html.
        try_files $uri $uri/ /index.html;
    }

    # Redirección al API Gateway NestJS con parche automático de versión
    location /api/ {
        # Mantiene el prefijo /api/v1/ de tus microservicios de NestJS de forma interna
        rewrite ^/api/(.*)$ /api/v1/$1 break;

        proxy_pass http://api-gateway:8080; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Cabeceras extra para asegurar IP real en los microservicios
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}