name: CI

on:
  pull_request:
    branches: [ "qa", "main" ]

jobs:
  pr-checks:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Verify format (Prettier)
        run: npx nx format:check --base=origin/${{ github.base_ref }}

      # AÑADIDO: --base=origin/${{ github.base_ref }} le dice a Nx que se compare con la rama destino del PR (ej. origin/qa)
      - name: Linting (Only services affected)
        run: npx nx affected -t lint --base=origin/${{ github.base_ref }}

      - name: Testing (Only services affected)
        run: npx nx affected -t test --base=origin/${{ github.base_ref }}

      - name: Build de prueba (Only services affected)
        run: npx nx affected -t build --base=origin/${{ github.base_ref }}

        