name: Infrastructure - Terraform GitOps

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'terraform/**' # VITAL! Only run if you change files inside the terraform folder
jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    # We inject temporary AWS credentials from GitHub secrets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout of the code
        uses: actions/checkout@v4

      - name: Configure Terraform in the Runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0 # You can use the version you have installed

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan (Changes Validation)
        id: plan
        run: |
          cd terraform
          terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply (Apply changes only to AWS)
        run: |
          cd terraform
          terraform apply -auto-approve