name: Infrastructure - Terraform GitOps

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'infrastructure/terraform/QA/**' # ¡Ruta actualizada para escuchar la carpeta correcta!

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    # 1. Llamamos a los secretos con prefijo QA_
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.QA_AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout of the code
        uses: actions/checkout@v4

      - name: Configure Terraform in the Runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        id: init
        run: |
          cd infrastructure/terraform/QA # Entrar a la carpeta exacta de QA
          terraform init

      - name: Terraform Plan (Changes Validation)
        id: plan
        run: |
          cd infrastructure/terraform/QA
          terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply (Apply changes only to AWS)
        run: |
          cd infrastructure/terraform/QA
          terraform apply -auto-approve